services:
  traefik:
    build:
      context: .
    volumes:
      - ./rootCert:/rootCert
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./docker/traefik/certificates.yaml:/etc/traefik/certificates.yaml
    ports:
      - 80:80
      - 443:443
      - 9000:8080
    restart: always
    networks:
      - traefik

networks:
  traefik:
    name: traefik
